### ISSUE TITLE
tile windows per monitor

### ISSUE THREAD

**Issue by higuita** [giuspen/x-tile#1]
I have a 2 monitor setup and i'm using fluxbox. I have some "permanent" windows on monitor 1 (on the left, chat, email, monitoring tools, etc) and in the monitor 2 (on the right), the main screen with many terminals, browsers and other tools

I also would like that apps in monitor 1 be tiled just in that monitor and apps in monitor 2 to be tiled only in monitor 2.

When trying to tile this config x-tile will mix the apps in monitor 1 with the apps in monitor 2, all in monitor 1 only. 
I think they should be tiled across both monitors and should be a options to keep windows on the same monitor

Thanks for xtile

**Comment by giuspen** [comment]
You are right, the problem is that at the moment I don't have the possibility to drvelop/test on a 2 monitors pc

**Comment by giuspen** [comment]
too old, open again if happens with latest
