### ISSUE TITLE
port to Python 3

### ISSUE THREAD

**Issue by david-geiger** [giuspen/x-tile#10]
Hi,

Is there a plan to port this project to Python 3? as python2 will be EOL on 2020

Regards,
David

**Comment by giuspen** [comment]
I have to complete the porting of my other app cherrytree first because has a much larger audience. x-tile porting to Python3-Gtk3 should not take too long then.

**Comment by david-geiger** [comment]
Any news about this port?

**Comment by giuspen** [comment]
I'm still into the porting of my other app that will take few more months, then ot will be the time
