### ISSUE TITLE
Glade isn't showing up

### ISSUE THREAD

**Issue by Raymo111** [giuspen/x-tile#19]
![Screenshot_20210916_174019](https://user-images.githubusercontent.com/34818275/133689421-1dacf220-4649-43d7-b9f0-ebee8e4e47a6.png)
Am I missing a dependency or something? (I installed from the [AUR](https://aur.archlinux.org/packages/x-tile/) and I also have glade installed. Clicking OK results in all the windows being tiled to the top left and I can set the positions manually from the config file just fine. Thanks for making this!

**Comment by giuspen** [comment]
try and run "x-tile" from a terminal, is it printing any error?

**Comment by Raymo111** [comment]
2 errors:
```bash
$ x-tile
WM = KWin
libc.prctl not available, the process name will be python and not x-tile # on launch
TypeError: Couldn't find foreign struct converter for 'cairo.Context' # on opening custom tile settings.
```
Based on that I installed the `python-cairo` package and it works now! Thanks.

Out of curiosity how do I fix the first error? I tried installing `python-prctl` but that didn't do anything, maybe I need to relogin for that to work?

**Comment by Raymo111** [comment]
The last AUR maintainer disowned the package and I adopted it and added the dependencies.

**Comment by giuspen** [comment]
I'm glad you found out 
The cairo.Context looks like a python gobject binding, I'm not familiar with archlinux, in Ubuntu I would try something like gir1.2-cairo-1.0

**Comment by Raymo111** [comment]
Yep yep. Thanks for your help!
